# Generated by Django 3.1 on 2020-08-15 23:43

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('mobile', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='title')),
                ('first_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Last Name')),
                ('other_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Other Names')),
                ('otp_token_uuid', models.CharField(blank=True, max_length=70, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
